name = "kalakritam-db-proxy-production"
main = "database-proxy-worker-production.js"
compatibility_date = "2024-01-01"

# No custom routes - accessed via workers.dev subdomain
# Example: https://kalakritam-db-proxy-production.gowthamnachu545.workers.dev

# Environment variables (set via wrangler secret put)
# Required:
# - NEON_DATABASE_URL: postgresql://username:password@host/database?sslmode=require
# - DB_PROXY_TOKEN: kalakritam-db-proxy-token-2025
#
# Optional:
# - NEON_API_KEY: your-neon-api-key

[build]
command = ""

[env.production]
name = "kalakritam-db-proxy-production"

[env.staging]
name = "kalakritam-db-proxy-staging"

# No additional bindings needed
