name = "kalakritam-api-production"
main = "KALAKRITAM_PRODUCTION_NO_SAMPLE_DATA.js"
compatibility_date = "2024-01-01"

# Production routes - configure these for your domain when domain is ready
# [[routes]]
# pattern = "api.kalakritam.in/*"
# zone_name = "kalakritam.in"

# Environment variables (set via wrangler secret put)
# Required:
# - DATABASE_PROXY_URL: https://kalakritam-db-proxy.gowthamnachu545.workers.dev
# - DB_PROXY_TOKEN: kalakritam-db-proxy-token-2025
# - JWT_SECRET: your-secure-jwt-secret-key-2025
# 
# Optional:
# - NODE_ENV: production

[build]
command = ""

[env.production]
name = "kalakritam-api-production"

[env.staging]
name = "kalakritam-api-staging"

# No D1 database needed - using external Neon via proxy
# No KV storage needed - no sample data fallback
