name = "kalakritam-frontend"
compatibility_date = "2024-08-12"
pages_build_output_dir = "dist"

[env.production]
  name = "kalakritam-production"
  compatibility_date = "2024-08-12"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"
